### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [horganke/project4#1]
It doesn't look like Bootstrap's JS plugins are working and I'm getting an error in the JavaScript console:

```
Uncaught Error: Bootstrap's JavaScript requires jQuery
```

If you're not sure how to fix this, let me know and I can help point you in the right direction.

**Comment by horganke** [comment]
Oops! Must have deleted the jquery link by accident. I'll fix and commit that thanks for letting me know!

**Comment by chrisvfritz** [comment]
Excellent. :smiley: Just let me know it's fixed.

**Comment by horganke** [comment]
Hey Chris. Hope you enjoy the 4 commits it took to fix this small error. Classic mistake, wasn't think about the scripts being processed top down and jquery was after bootstrap causing that error

**Comment by chrisvfritz** [comment]
:+1: Looks good! For the future, you may find [`git commit --amend`](https://www.atlassian.com/git/tutorials/rewriting-history/git-commit--amend/) helpful for those times when you try something out and it turns out not to actually work. It happens to us all! :smiley:
